# Generated by Django 4.1.1 on 2023-01-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pactientaccount',
            name='mobilenumber',
            field=models.IntegerField(unique=True),
        ),
    ]
