# Generated by Django 4.1.1 on 2023-01-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_bookedsession_email_recep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedsession',
            name='data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookedsession',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
